// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdE0oQk9pdBkGm2XrTi2Q_uh89gBcQi_w',
    appId: '1:851348159510:web:1e2c6018208a4d6e374937',
    messagingSenderId: '851348159510',
    projectId: 'login-signup-30894',
    authDomain: 'login-signup-30894.firebaseapp.com',
    storageBucket: 'login-signup-30894.firebasestorage.app',
    measurementId: 'G-VQRFHJ50XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbf1ZltE9KHRgoYRa6HNDqiJ8J6GgN3nY',
    appId: '1:851348159510:android:7f297a2632840897374937',
    messagingSenderId: '851348159510',
    projectId: 'login-signup-30894',
    storageBucket: 'login-signup-30894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhhL9aT2CggX0YXHQu5lk75mOs6ksU0w',
    appId: '1:851348159510:ios:c2514e33cafb85f4374937',
    messagingSenderId: '851348159510',
    projectId: 'login-signup-30894',
    storageBucket: 'login-signup-30894.firebasestorage.app',
    iosClientId: '851348159510-3a8j7a8hs8t8ui74rong67joqo65b8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPhhL9aT2CggX0YXHQu5lk75mOs6ksU0w',
    appId: '1:851348159510:ios:c2514e33cafb85f4374937',
    messagingSenderId: '851348159510',
    projectId: 'login-signup-30894',
    storageBucket: 'login-signup-30894.firebasestorage.app',
    iosClientId: '851348159510-3a8j7a8hs8t8ui74rong67joqo65b8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdE0oQk9pdBkGm2XrTi2Q_uh89gBcQi_w',
    appId: '1:851348159510:web:eba4fc5a2e9820ff374937',
    messagingSenderId: '851348159510',
    projectId: 'login-signup-30894',
    authDomain: 'login-signup-30894.firebaseapp.com',
    storageBucket: 'login-signup-30894.firebasestorage.app',
    measurementId: 'G-L9QXBF3GGT',
  );
}
